### ISSUE TITLE
Read -1, expected 5285, errno = 1

### ISSUE THREAD

**Issue by xiaoruiDu** [ornladios/ADIOS2-Examples#62]
Dear ADIOS2 Community,
I am runing gray-scott example. The program can run without crash but give me this read error when I launch it
`
mpirun --allow-run-as-root -n 4 adios2-gray-scott settings-files.json

[de44f6097ee6:39278] Read -1, expected 5285, errno = 1
[de44f6097ee6:39279] Read -1, expected 5285, errno = 1
[de44f6097ee6:39280] Read -1, expected 5285, errno = 1

`
any idea?

more output:

<img width="530" alt="31F73B13-DB60-45E5-A0D7-97ED2DA2D981" src="https://user-images.githubusercontent.com/34736859/172576959-a756c660-a0ec-4e78-8cc9-9e5eabdaac5b.png">

**Comment by pnorbert** [comment]
What version/commit of ADIOS2 and ADIOS2-Examples are you using?
Why do you need that root flag for mpirun? Are you sure your are running the executable file that you expect, or may the system find another version in your path?

I have never seen this error, and I just tried with ADIOS2 and ADIOS2-Examples master branch but I don't get anything like this.

**Comment by xiaoruiDu** [comment]
> 

hey, thanks for you fast reply. I run adios2(adios2-example) in docker container '--allow-run-as-root' is for docker reason. 

I also use adios2 master branch. Is it possible that this error is only for docker?

**Comment by xiaoruiDu** [comment]
by the way, it can run without any error if i set process number to 1.  
`mpirun --allow-run-as-root -n 1 adios2-gray-scott settings-files.json`.

**Comment by pnorbert** [comment]
Do you get this error messages if you run other programs with multiple processes? The error message does not come from ADIOS2.

**Comment by pnorbert** [comment]
see https://github.com/horovod/horovod/issues/503

**Comment by xiaoruiDu** [comment]
> see [horovod/horovod#503](https://github.com/horovod/horovod/issues/503)

thanks for this hint. I already spent 2 days on this error. Now, problem solved with setting enviroment varible before lunching the job.

`export OMPI_MCA_btl_vader_single_copy_mechanism=none`

[https://github.com/open-mpi/ompi/issues/4948#issuecomment-395468231](url)
